title: sircus
description: Moduler CSS For People Who Make Web Together.
copyright: Copyright (c) 2015 blivesta and ungki. all rights reserved.
author: blivesta
author_url: http://blivesta.com
maintainer: ungki
maintainer_url: https://github.com/ungki
tags: sircus, scalable css, moduler css, cssnext, postcss
twitter: blivesta
sircus_url: http://sircus.blivesta.com
github_url: https://github.com/sircus/sircus
git_star_btn: http://ghbtns.com/github-btn.html?user=sircus&repo=sircus&type=watch&count=true
